config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :posts do
    resources :comments, only: [:create, :destroy]
  end
 
  get ':user_name', to: 'profile#show', as: :profile

  root 'posts#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text,    presence: true
  validates :user_id, presence: true
  
  belongs_to :commentable
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  validates :user_id, presence: true

  has_attached_file :image, styles: { medium: '640x' }
  validates_attachment :image, presence: true,
                               content_type: { content_type: %r{\Aimage/.*\Z} },
                               size: { in: 0..2.megabytes }

  belongs_to :user
  has_many :comments, as: :commentable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  store :preferences, accessors: [:display_type]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar,
                    styles: { thumb: '100x100#', medium: '400x400#' },
                    default_url: '/images/profile-holder.png'

  validates_attachment :avatar,
                       content_type: { content_type: %r{\Aimage/.*\Z} },
                       size: { in: 0..2.megabytes }

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  expose :context, -> { context_object }

  def create
    @comment = context.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      redirect_to root_path, alert: 'Something went wrong.'
    end
  end

  def destroy
    comment.destroy
    respond_to do |format|
      format.html do
        redirect_to comments_url,
                    notice: 'Comment was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

    def comment_params
      params.require(:comment).permit(:text)
    end

    def context_object
      Post.find_by(id: params[:post_id]) if params[:post_id]
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :post_owner, only: %i[edit update destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_post

  expose :posts, -> { Post.order('created_at desc').includes(:user, :comments) }
  expose :post

  def index; end

  def show; end

  def new; end

  def edit; end

  def create
    post = Post.new(post_params)
    post.user_id = current_user.id

    respond_to do |format|
      if post.save
        format.html do
          redirect_to post,
                      notice: 'Post was successfully created.'
        end
        format.json { render :show, status: :created, location: post }
      else
        format.html { render :new }
        format.json { render json: post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if post.update(post_params)
        format.html do
          redirect_to post,
                      notice: 'Post was successfully updated.'
        end
        format.json { render :show, status: :ok, location: post }
      else
        format.html { render :edit }
        format.json { render json: post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    post.destroy
    respond_to do |format|
      format.html do
        redirect_to posts_url,
                    notice: 'Post was successfully destroyed.'
      end
      format.json { head :no_content }
    end
  end

  private

    def post_params
      params.require(:post).permit(:caption, :image)
    end

    def post_owner
      owner = (current_user == post.user)
      unless owner
        redirect_to root_path,
                    alert: 'Something went wrong.'
      end
    end

    def invalid_post
      logger.error "Attempt to access invalid post #{params[:id]}"
      redirect_to root_url, alert: 'Invalid post'
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
  expose :user, -> { User.find_by(username: params[:user_name]) }
  expose :posts, -> { user.posts.order('created_at desc') }

  def show; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
    { success: 'alert-success',
      error: 'alert-danger',
      alert: 'alert-warning',
      notice: 'alert-info' }[flash_type.to_sym] || flash_type.to_s
  end

  def icon_link(link_path, icon)
    link_to raw("<i class='material-icons'>#{icon}</i>"), link_path
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/comments/_comment.html.haml
.comment-item
  .user-name
    = link_to comment.user.username, profile_path(comment.user.username)
  .comment-text
    = comment.text

app/views/comments/_form.html.haml
= simple_form_for(@comment) do |f|
  = f.error_notification

  .form-inputs
    = f.input :user_id
    = f.input :text
    = f.association :commentable

  .form-actions
    = f.button :submit

app/views/comments/create.js.erb
$('#comments_<%= context.id %>').append("<%=j render'comments/comment', post: context, comment: @comment %>");
$('#comment_field_<%= context.id %>').val('')

app/views/comments/edit.html.haml
%h1 Editing comment

= render 'form'

= link_to 'Show', @comment
\|
= link_to 'Back', comments_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Instaphotos
    = csrf_meta_tags
    = favicon_link_tag 'fav.png'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}

  %body
    .header
      = render 'shared/header'
      
    .container
      -flash.each do |name, msg|
        = content_tag :div, msg, class: [:alert, alert_for(name)]

      = yield

app/views/posts/_form.html.haml
= simple_form_for(post) do |f|
  = f.error_notification

  .form-inputs
    = f.input :caption
    = f.input :image

  .form-actions
    = f.button :submit

app/views/posts/_post.html.haml
%li
  .card
    .user-info
      = link_to post.user.username, profile_path(post.user.username)

    .post-image
      = image_tag post.image.url(:medium)

    .post-extras
      .post-caption
        = post.caption

      .post-comments
        .post-commments-list{id: "comments_#{post.id}"}
          - if post.comments
            = render post.comments, post: post

        .comments-form
          = form_for [post, post.comments.new] , remote: true do |f|
            = f.text_field :text, required: true, placeholder: 'Add a comment...', id: "comment_field_#{post.id}"

app/views/posts/edit.html.haml
%h1 Editing post

= render 'form'

= link_to 'Show', post
\|
= link_to 'Back', posts_path

app/views/posts/index.html.haml
%ul.post_list
  = render posts
    

app/views/posts/new.html.haml
%h1 New post

= render 'form'

= link_to 'Back', posts_path

app/views/posts/show.html.haml
%ul.post_list
 = render post

= link_to 'Edit', edit_post_path(post)
\|
= link_to 'Back', posts_path

app/views/shared/_header.html.haml
.header-wrapper
  .row
    .col.s4
      = render 'shared/logo'
    .col.s4
      = render 'shared/search'
    .col.s4
      = render 'shared/user_menu'

app/views/shared/_logo.html.haml
.logo-place
  .logo-ico
    = icon_link(root_path, 'camera')
  .logo
    = link_to image_tag('logo.png'), root_path

app/views/shared/_search.html.haml
.search
  =form_tag("/") do
    .search_field
      =text_field_tag :q,'', placeholder: 'Search'

app/views/shared/_user_menu.html.haml
%ul.right.user-menu
  - if user_signed_in?
    %li
      = icon_link(posts_path, 'favorite_border')
    %li
      = icon_link(new_post_path, 'add_a_photo')
    %li
      = icon_link(profile_path(current_user.username), 'perm_identity')